mark 1 of the dojo
SethBailey/Sparks pull request #20
Opened 2020-05-19 12:32 UTC by SethBailey

2020-05-19 16:18 UTC, Stackingit requested changes

2020-05-19 16:18 UTC, Stackingit commented on Program.cs
> +                        }
Perhaps we could also pull out the common code.. the only thing unique is the monster, and the award ?

2020-05-19 16:18 UTC, Stackingit commented on Program.cs
> +                return;
The return here is not needed

2020-05-19 16:18 UTC, Stackingit commented on Program.cs
> +                if (Awnser == "yes")
spelling, capital

2020-05-19 16:42 UTC, SethBailey commented on Program.cs
> +                TypeWriter.WriteLine("or (l) to leave");
no but now it is fixed

2020-05-19 16:48 UTC, SethBailey commented on Program.cs
> +                string Awnser = GetLowerReply();
fixed

2020-05-20 14:47 UTC, SethBailey commented on Program.cs
> +       bool canPlayerRun = true;
based on what the bool does it's just more descriptive

2020-06-10 12:20 UTC, merged